# Generated by Django 4.0.2 on 2022-02-22 08:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_info_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userimages/'),
        ),
    ]
