# Generated by Django 4.0.2 on 2022-02-23 06:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_info_age'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='info',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
