# Generated by Django 4.0.2 on 2022-02-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_info_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='info',
            managers=[
            ],
        ),
    ]
