# Generated by Django 4.0.2 on 2022-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_info_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='info',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
