# Generated by Django 4.0.2 on 2022-02-23 18:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_info_show_email_info_show_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
