# Generated by Django 4.0.2 on 2022-02-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='genre',
            new_name='category',
        ),
    ]
