# Generated by Django 4.0.2 on 2022-02-16 07:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_description_alter_article_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
