# Generated by Django 4.0.2 on 2022-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Technologies', 'Technologies'), ('Nature', 'Nature')], default='Other', max_length=100),
        ),
    ]
