# Generated by Django 4.0.2 on 2022-03-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_category_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Other', 'Other'), ('Technologies', 'Technologies'), ('Nature', 'Nature')], default='Other', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
